import "../styles/globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/context/auth";
import StaticNavbar from "@/components/navbar/staticNavbar";
import StickyNavbar from "@/components/navbar/stickyNavbar";
import { AppProvider } from "@/context/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WTA",
  keywords: "WTA, Web Technologies Academy",
  description: "Generated by create Web Technologies Academy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + "h-screen"}>
        <AuthProvider>
          <AppProvider>
            <StaticNavbar />
            <StickyNavbar />
            <main id="content" role="main">
              {children}
            </main>
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
